### ISSUE TITLE
eksa-admin node should include unattended-upgrades

### ISSUE THREAD

**Issue by displague** [equinix-labs/terraform-equinix-metal-eks-anywhere#37]
The EKS-A Admin node is running Ubuntu 20.04. We should ensure the latest updates are installed and continue to be installed through use of the unattended-upgrades package.

**Comment by cprivitere** [comment]
Adding the following to the cloud-init should do it.

```yaml
- sed 's,//      "${distro_id}:${distro_codename}-updates";,        "${distro_id}:${distro_codename}-updates";,' /etc/apt/apt.conf.d/50unattended-upgrades
- sed 's,//Unattended-Upgrade::Automatic-Reboot "false";,Unattended-Upgrade::Automatic-Reboot "true";,' /etc/apt/apt.conf.d/50unattended-upgrades
```

**Comment by displague** [comment]
We'll also want to ensure (somehow) that the node isn't rebooted while the cluster is coming up for the first time.
Maybe we can disable it at install and `at` schedule the enablement for a few hours later.

**Comment by cprivitere** [comment]
Options:
- disable autoreboot
- Set reboot time to 2AM
- Do your at scheme.
- Calculate the autoreboot time to be 2 hours (or some other offset) from current time.

**Comment by cprivitere** [comment]
Looks like the upfront upgrade (package_upgrade: true) may be a bad idea. Adds 15 minutes plus to the initial deployment.
