### ISSUE TITLE
systemctl restart networking fails sometimes

### ISSUE THREAD

**Issue by displague** [equinix-labs/terraform-equinix-metal-eks-anywhere#9]
`systemctl restart networking` fails sometimes after changing the network mode and bonding and attaching VLANs.

**Comment by enkelprifti98** [comment]
@displague I'm guessing you're referring to this step?

https://github.com/equinix-labs/terraform-equinix-metal-eks-anywhere/blob/main/setup.cloud-init.tftpl#L44

Why not use `ifup bond0.${vlan_vnid}` instead? From my experience restarting the entire network stack is really needed when you changing the underlying bond interface but with VLAN interfaces it's not necessary.

**Comment by displague** [comment]
We haven't seen this problem in recent deploys.

I'm not sure if we have the ifupdown tools installed.
If it's installed we can attempt this approach, otherwise I think it is safe to close this.
